# Exported from Render on 2026-09-14T16:56:53Z
version: "1"
projects:
  - name: QuestForge
    environments:
      - name: Production
        services:
          - type: web
            name: QuestForge-backend
            runtime: node
            repo: https://github.com/aayush-6753/QuestForge
            plan: free
            envVars:
              - key: CLIENT_ORIGINS
                value: https://life-rpg-frontend.onrender.com
              - key: SUPABASE_ANON_KEY
                sync: false
              - key: SUPABASE_URL
                sync: false
              - key: DIRECT_URL
                sync: false
              - key: DATABASE_URL
                sync: false
              - key: PORT
                sync: false
              - key: NODE_ENV
                sync: false
            region: oregon
            buildCommand: npm install && npm run build
            startCommand: npm start
            healthCheckPath: /api/health
            autoDeployTrigger: commit
            rootDir: backend
